# Generated by Django 4.1 on 2023-02-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade_Five',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ተ_ቁ', models.CharField(max_length=30)),
                ('ተማሪው_ዋ_ስም', models.CharField(max_length=30)),
                ('ፆታ', models.CharField(max_length=30)),
                ('አማርኛ', models.CharField(max_length=15)),
                ('English', models.CharField(max_length=3)),
                ('Maths', models.CharField(max_length=3)),
                ('G_science', models.CharField(max_length=3)),
                ('ህ_ሰብ', models.CharField(max_length=3)),
                ('ዜግነት', models.CharField(max_length=3)),
                ('ጤናና_ሰ_ማጎ', models.CharField(max_length=3)),
                ('ሥነጥበባት', models.CharField(max_length=3)),
                ('ድምር', models.CharField(max_length=3)),
                ('አማካይ', models.CharField(max_length=3)),
                ('ደረጃ', models.CharField(max_length=3)),
                ('ምርመራ', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'Grade_Five',
            },
        ),
        migrations.CreateModel(
            name='Grade_Four',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ተ_ቁ', models.CharField(max_length=30)),
                ('ተማሪው_ዋ_ስም', models.CharField(max_length=30)),
                ('ፆታ', models.CharField(max_length=30)),
                ('አማርኛ', models.CharField(max_length=15)),
                ('English', models.CharField(max_length=3)),
                ('Maths', models.CharField(max_length=3)),
                ('G_science', models.CharField(max_length=3)),
                ('ህ_ሰብ', models.CharField(max_length=3)),
                ('ዜግነት', models.CharField(max_length=3)),
                ('ጤናና_ሰ_ማጎ', models.CharField(max_length=3)),
                ('ሥነጥበባት', models.CharField(max_length=3)),
                ('ድምር', models.CharField(max_length=3)),
                ('አማካይ', models.CharField(max_length=3)),
                ('ደረጃ', models.CharField(max_length=3)),
                ('ምርመራ', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'Grade_Four',
            },
        ),
        migrations.CreateModel(
            name='Grade_One',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ተ_ቁ', models.CharField(max_length=30)),
                ('ተማሪው_ዋ_ስም', models.CharField(max_length=30)),
                ('ፆታ', models.CharField(max_length=30)),
                ('አማርኛ', models.CharField(max_length=15)),
                ('English', models.CharField(max_length=3)),
                ('Maths', models.CharField(max_length=3)),
                ('G_science', models.CharField(max_length=3)),
                ('ህ_ሰብ', models.CharField(max_length=3)),
                ('ዜግነት', models.CharField(max_length=3)),
                ('ጤናና_ሰ_ማጎ', models.CharField(max_length=3)),
                ('ሥነጥበባት', models.CharField(max_length=3)),
                ('ድምር', models.CharField(max_length=3)),
                ('አማካይ', models.CharField(max_length=3)),
                ('ደረጃ', models.CharField(max_length=3)),
                ('ምርመራ', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'Grade_One',
            },
        ),
        migrations.CreateModel(
            name='Grade_Six',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ተ_ቁ', models.CharField(max_length=30)),
                ('ተማሪው_ዋ_ስም', models.CharField(max_length=30)),
                ('ፆታ', models.CharField(max_length=30)),
                ('አማርኛ', models.CharField(max_length=15)),
                ('English', models.CharField(max_length=3)),
                ('Maths', models.CharField(max_length=3)),
                ('G_science', models.CharField(max_length=3)),
                ('ህ_ሰብ', models.CharField(max_length=3)),
                ('ዜግነት', models.CharField(max_length=3)),
                ('ጤናና_ሰ_ማጎ', models.CharField(max_length=3)),
                ('ሥነጥበባት', models.CharField(max_length=3)),
                ('ድምር', models.CharField(max_length=3)),
                ('አማካይ', models.CharField(max_length=3)),
                ('ደረጃ', models.CharField(max_length=3)),
                ('ምርመራ', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'Grade_Six',
            },
        ),
        migrations.CreateModel(
            name='Grade_Three',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ተ_ቁ', models.CharField(max_length=30)),
                ('ተማሪው_ዋ_ስም', models.CharField(max_length=30)),
                ('ፆታ', models.CharField(max_length=30)),
                ('አማርኛ', models.CharField(max_length=15)),
                ('English', models.CharField(max_length=3)),
                ('Maths', models.CharField(max_length=3)),
                ('G_science', models.CharField(max_length=3)),
                ('ህ_ሰብ', models.CharField(max_length=3)),
                ('ዜግነት', models.CharField(max_length=3)),
                ('ጤናና_ሰ_ማጎ', models.CharField(max_length=3)),
                ('ሥነጥበባት', models.CharField(max_length=3)),
                ('ድምር', models.CharField(max_length=3)),
                ('አማካይ', models.CharField(max_length=3)),
                ('ደረጃ', models.CharField(max_length=3)),
                ('ምርመራ', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'Grade_Three',
            },
        ),
        migrations.CreateModel(
            name='Grade_Two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ተ_ቁ', models.CharField(max_length=30)),
                ('ተማሪው_ዋ_ስም', models.CharField(max_length=30)),
                ('ፆታ', models.CharField(max_length=30)),
                ('አማርኛ', models.CharField(max_length=15)),
                ('English', models.CharField(max_length=3)),
                ('Maths', models.CharField(max_length=3)),
                ('G_science', models.CharField(max_length=3)),
                ('ህ_ሰብ', models.CharField(max_length=3)),
                ('ዜግነት', models.CharField(max_length=3)),
                ('ጤናና_ሰ_ማጎ', models.CharField(max_length=3)),
                ('ሥነጥበባት', models.CharField(max_length=3)),
                ('ድምር', models.CharField(max_length=3)),
                ('አማካይ', models.CharField(max_length=3)),
                ('ደረጃ', models.CharField(max_length=3)),
                ('ምርመራ', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'Grade_Two',
            },
        ),
        migrations.DeleteModel(
            name='Grade_Eleven',
        ),
        migrations.DeleteModel(
            name='Grade_Nine',
        ),
        migrations.DeleteModel(
            name='Grade_Ten',
        ),
        migrations.DeleteModel(
            name='Grade_Twelve',
        ),
    ]
