# Generated by Django 4.1 on 2023-02-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xl', '0002_grade_five_grade_four_grade_one_grade_six_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade_Eight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ተ_ቁ', models.CharField(max_length=30)),
                ('ተማሪው_ዋ_ስም', models.CharField(max_length=30)),
                ('ፆታ', models.CharField(max_length=30)),
                ('አማርኛ', models.CharField(max_length=15)),
                ('English', models.CharField(max_length=3)),
                ('Maths', models.CharField(max_length=3)),
                ('G_science', models.CharField(max_length=3)),
                ('ህ_ሰብ', models.CharField(max_length=3)),
                ('ዜግነት', models.CharField(max_length=3)),
                ('ጤናና_ሰ_ማጎ', models.CharField(max_length=3)),
                ('ሥነጥበባት', models.CharField(max_length=3)),
                ('ድምር', models.CharField(max_length=3)),
                ('አማካይ', models.CharField(max_length=3)),
                ('ደረጃ', models.CharField(max_length=3)),
                ('ምርመራ', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'Grade_eight',
            },
        ),
        migrations.CreateModel(
            name='Grade_Seven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ተ_ቁ', models.CharField(max_length=30)),
                ('ተማሪው_ዋ_ስም', models.CharField(max_length=30)),
                ('ፆታ', models.CharField(max_length=30)),
                ('አማርኛ', models.CharField(max_length=15)),
                ('English', models.CharField(max_length=3)),
                ('Maths', models.CharField(max_length=3)),
                ('G_science', models.CharField(max_length=3)),
                ('ህ_ሰብ', models.CharField(max_length=3)),
                ('ዜግነት', models.CharField(max_length=3)),
                ('ጤናና_ሰ_ማጎ', models.CharField(max_length=3)),
                ('ሥነጥበባት', models.CharField(max_length=3)),
                ('ድምር', models.CharField(max_length=3)),
                ('አማካይ', models.CharField(max_length=3)),
                ('ደረጃ', models.CharField(max_length=3)),
                ('ምርመራ', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'Grade_Seven',
            },
        ),
    ]
