# Generated by Django 4.1 on 2023-02-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xl', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual_Grade_Eight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('test_subjects', models.CharField(max_length=15)),
                ('test_one', models.CharField(max_length=3)),
                ('test_two', models.CharField(max_length=3)),
                ('mid', models.CharField(max_length=3)),
                ('test_three', models.CharField(max_length=3)),
                ('final', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Manual_Grade_Five',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('test_subjects', models.CharField(max_length=15)),
                ('test_one', models.CharField(max_length=3)),
                ('test_two', models.CharField(max_length=3)),
                ('mid', models.CharField(max_length=3)),
                ('test_three', models.CharField(max_length=3)),
                ('final', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Manual_Grade_Four',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('test_subjects', models.CharField(max_length=15)),
                ('test_one', models.CharField(max_length=3)),
                ('test_two', models.CharField(max_length=3)),
                ('mid', models.CharField(max_length=3)),
                ('test_three', models.CharField(max_length=3)),
                ('final', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Manual_Grade_One',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('test_subjects', models.CharField(max_length=15)),
                ('test_one', models.CharField(max_length=3)),
                ('test_two', models.CharField(max_length=3)),
                ('mid', models.CharField(max_length=3)),
                ('test_three', models.CharField(max_length=3)),
                ('final', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Manual_Grade_Seven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('test_subjects', models.CharField(max_length=15)),
                ('test_one', models.CharField(max_length=3)),
                ('test_two', models.CharField(max_length=3)),
                ('mid', models.CharField(max_length=3)),
                ('test_three', models.CharField(max_length=3)),
                ('final', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Manual_Grade_Six',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('test_subjects', models.CharField(max_length=15)),
                ('test_one', models.CharField(max_length=3)),
                ('test_two', models.CharField(max_length=3)),
                ('mid', models.CharField(max_length=3)),
                ('test_three', models.CharField(max_length=3)),
                ('final', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Manual_Grade_Three',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('test_subjects', models.CharField(max_length=15)),
                ('test_one', models.CharField(max_length=3)),
                ('test_two', models.CharField(max_length=3)),
                ('mid', models.CharField(max_length=3)),
                ('test_three', models.CharField(max_length=3)),
                ('final', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Manual_Grade_Two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('test_subjects', models.CharField(max_length=15)),
                ('test_one', models.CharField(max_length=3)),
                ('test_two', models.CharField(max_length=3)),
                ('mid', models.CharField(max_length=3)),
                ('test_three', models.CharField(max_length=3)),
                ('final', models.CharField(max_length=3)),
            ],
        ),
    ]
