# Generated by Django 4.1 on 2023-02-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xl', '0005_manual_grade_eight_manual_grade_five_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade_one',
            name='አማርኛ',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='grade_one',
            name='ፆታ',
            field=models.CharField(max_length=15),
        ),
    ]
