# Generated by Django 4.1 on 2023-02-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xl', '0006_alter_grade_one_አማርኛ_alter_grade_one_ፆታ'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manual_Grade_Eight',
        ),
        migrations.DeleteModel(
            name='Manual_Grade_Five',
        ),
        migrations.DeleteModel(
            name='Manual_Grade_Four',
        ),
        migrations.DeleteModel(
            name='Manual_Grade_One',
        ),
        migrations.DeleteModel(
            name='Manual_Grade_Seven',
        ),
        migrations.DeleteModel(
            name='Manual_Grade_Six',
        ),
        migrations.DeleteModel(
            name='Manual_Grade_Three',
        ),
        migrations.DeleteModel(
            name='Manual_Grade_Two',
        ),
        migrations.AlterField(
            model_name='grade_eight',
            name='አማርኛ',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='grade_eight',
            name='ፆታ',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='grade_five',
            name='አማርኛ',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='grade_five',
            name='ፆታ',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='grade_four',
            name='አማርኛ',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='grade_four',
            name='ፆታ',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='grade_seven',
            name='አማርኛ',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='grade_seven',
            name='ፆታ',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='grade_six',
            name='አማርኛ',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='grade_six',
            name='ፆታ',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='grade_three',
            name='አማርኛ',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='grade_three',
            name='ፆታ',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='grade_two',
            name='አማርኛ',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='grade_two',
            name='ፆታ',
            field=models.CharField(max_length=15),
        ),
    ]
